version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/nginx/html:/usr/share/nginx/html
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  cnts:
    image: cnts:latest
    build: .
    ports:
      - "8080:8080"

